### ISSUE TITLE
Doesn't seem to work in Kodi

### ISSUE THREAD

**Issue by milezzz** [djay/service.subtitles.thaisubtitle#1]
Really appreciate you building this!

I am on Kodi 14.1 and it didn't seem to work.  I always get a script error.  I'll post the log but for now but I can't seem to get the log viewer working either _sigh_.

I did run it from the command line and it works there so I am hopeful.  I had to install beautifulsoup.  I also made sure that was installed in Kodi.  Is there anything else that is required in Kodi for this to function?  Perhaps the correct Thai font?

**Comment by tripats** [comment]
Yepp, this is the error from the kodi log
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: log() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/service.subtitles.thaisubtitle-master/service.py", line 311, in <module>
                                                log('Using preferred language: %s' % preferred_language)
                                            TypeError: log() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--

**Comment by djay** [comment]
now fixed

**Comment by milezzz** [comment]
@djay is da man.

**Comment by djay** [comment]
I’ve submitted it to the main kodi repo. I think if its accepted then it should update automatically.
